#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

pip install poetry
# We're in Docker, so we don't need a VENV
poetry config virtualenvs.create false
poetry install --no-interaction

# Keep this inline with any requirements that are in manifest.json
pip install git+https://github.com/zabuldon/teslajsonpy.git@dev#teslajsonpy==3.9.9
pre-commit install --install-hooks
