#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

pip install poetry
pip install pre-commit
pip install homeassistant

poetry lock
poetry install --no-root

# Keep this inline with any requirements that are in manifest.json
pip install git+https://github.com/zabuldon/teslajsonpy.git@dev#teslajsonpy==3.13.0

git config --global --add safe.directory /workspaces/tesla
pre-commit install --install-hooks
